// Batch importer for the French vocabulary deck. Parses CSV or JSON, runs every
// row through the same domain validation the trainer uses (cleanFrenchWord), and
// returns the accepted words plus a per-row report of what was rejected and why.
//
// Pure (no fs / no Supabase) so it is unit tested directly; scripts/import-
// vocabulary.mjs is the thin CLI wrapper that reads a file and prints the report.

import { cleanFrenchWord } from './srsScheduler.js'

/**
 * Minimal RFC-4180-ish CSV parser: handles quoted fields, escaped quotes (""),
 * and commas / newlines inside quotes. Returns an array of string-cell rows.
 */
export function parseCsv(text) {
  const rows = []
  let row = []
  let field = ''
  let inQuotes = false
  let sawAny = false

  for (let i = 0; i < text.length; i += 1) {
    const c = text[i]
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') {
          field += '"'
          i += 1
        } else {
          inQuotes = false
        }
      } else {
        field += c
      }
    } else if (c === '"') {
      inQuotes = true
      sawAny = true
    } else if (c === ',') {
      row.push(field)
      field = ''
      sawAny = true
    } else if (c === '\n') {
      row.push(field)
      rows.push(row)
      row = []
      field = ''
      sawAny = false
    } else if (c !== '\r') {
      field += c
      sawAny = true
    }
  }
  if (inQuotes) throw new Error('CSV 有一处引号没有闭合。原文件未改，请修正后重试。')
  if (sawAny || field.length || row.length) {
    row.push(field)
    rows.push(row)
  }
  return rows
}

/**
 * Turn header + data rows into row objects keyed by trimmed header names.
 * Blank lines (all-empty cells) are skipped.
 */
export function csvToObjects(text) {
  const rows = parseCsv(text).filter((r) => r.some((cell) => `${cell}`.trim() !== ''))
  if (rows.length < 2) return []
  const headers = rows[0].map((h) => `${h}`.trim())
  return rows.slice(1).map((cells) => {
    const obj = {}
    headers.forEach((h, idx) => {
      obj[h] = cells[idx] !== undefined ? `${cells[idx]}`.trim() : ''
    })
    return obj
  })
}

function detectFormat(text, hint) {
  if (hint === 'csv' || hint === 'json') return hint
  const trimmed = text.trim()
  return trimmed.startsWith('[') || trimmed.startsWith('{') ? 'json' : 'csv'
}

function deriveId(word) {
  if (word.id) return `${word.id}`.trim()
  // stable slug from the french headword
  return `fr-${`${word.french}`
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '') // strip combining accents
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')}`
}

/**
 * Import a raw CSV/JSON string into a validated deck.
 * Returns { words, report } where:
 *   words  = accepted, validated, de-duplicated word objects (with a stable id)
 *   report = { total, accepted, rejected:[{index,french,errors}], duplicates:[{index,id}] }
 */
export function importVocabulary(text, { format } = {}) {
  const fmt = detectFormat(text, format)

  let rawRows
  if (fmt === 'json') {
    const parsed = JSON.parse(text)
    rawRows = Array.isArray(parsed) ? parsed : [parsed]
  } else {
    rawRows = csvToObjects(text)
  }

  const words = []
  const rejected = []
  const duplicates = []
  const seenIds = new Set()

  rawRows.forEach((raw, index) => {
    const { ok, errors, word } = cleanFrenchWord(raw)
    if (!ok) {
      rejected.push({ index, french: `${raw?.french ?? ''}`.trim(), errors })
      return
    }
    const id = deriveId(word)
    if (!id) {
      rejected.push({ index, french: word.french, errors: ['词条 ID 不能为空白。'] })
      return
    }
    if (seenIds.has(id)) {
      duplicates.push({ index, id })
      return
    }
    seenIds.add(id)
    words.push({ ...word, id })
  })

  return {
    words,
    report: {
      total: rawRows.length,
      accepted: words.length,
      rejected,
      duplicates,
    },
  }
}

/**
 * Render the validated deck as a frenchVocabulary.js module source string,
 * ready to write over src/data/frenchVocabulary.js.
 */
export function toDataModuleSource(words) {
  const body = words.map((w) => `  ${JSON.stringify(w)},`).join('\n')
  return `// Generated by scripts/import-vocabulary.mjs — do not hand-edit; re-run the importer.
export const frenchVocabulary = [
${body}
]

export default frenchVocabulary
`
}

// 校验失败时禁止写文件，避免用部分词条覆盖整份词库。
export function assertVocabularyWrite({ words, report }, previous = []) {
  if (!words.length || report.rejected.length || report.duplicates.length) {
    throw new Error('词表有错误、重复 ID 或没有有效词条。原文件未改，请修正后重试。')
  }
  const ids = new Set(words.map((word) => word.id))
  const missing = previous.filter((word) => !ids.has(word.id))
  if (missing.length) throw new Error(`导入会丢失 ${missing.length} 个现有词条 ID。原文件未改；请保留旧 ID。`)
  const oldIdsByFrench = new Map()
  for (const word of previous) {
    const ids = oldIdsByFrench.get(word.french) || new Set()
    ids.add(word.id)
    oldIdsByFrench.set(word.french, ids)
  }
  const changed = words.filter((word) => oldIdsByFrench.has(word.french) && !oldIdsByFrench.get(word.french).has(word.id))
  if (changed.length) throw new Error(`有 ${changed.length} 个现有词被分配了别的 ID。原文件未改；请保留词与 ID 的对应关系。`)
}
