-- 混合历史建表脚本：包含现役 resources 和退役相册表，不是当前安装步骤。
-- 保留 SQL 供核对；执行前必须核实目标库的已有结构与权限。

create table if not exists public.albums (
  id bigint generated by default as identity primary key,
  title text not null,
  description text default '',
  featured boolean default false,
  cover text default '',
  date date,
  updated_at timestamptz default now(),
  location text default '',
  recorded_by text default '',
  source_submission_id bigint unique,
  published_by uuid references auth.users(id) on delete set null
);

create table if not exists public.album_photos (
  id bigint generated by default as identity primary key,
  album_id bigint not null references public.albums(id) on delete cascade,
  src text not null,
  caption text default '',
  position integer default 0
);

create table if not exists public.resources (
  id bigint generated by default as identity primary key,
  category text default '未分类',
  title text not null,
  url text default '',
  tag text default '',
  description text default '',
  curator text default '',
  created_at timestamptz default now(),
  source_submission_id bigint unique,
  published_by uuid references auth.users(id) on delete set null
);

create index if not exists albums_source_submission_id_idx on public.albums (source_submission_id);
create index if not exists album_photos_album_id_idx on public.album_photos (album_id, position);
create index if not exists resources_source_submission_id_idx on public.resources (source_submission_id);

alter table public.albums enable row level security;
alter table public.album_photos enable row level security;
alter table public.resources enable row level security;

drop policy if exists "Public albums are viewable by everyone" on public.albums;
create policy "Public albums are viewable by everyone"
on public.albums
for select
to public
using (true);

drop policy if exists "Public album photos are viewable by everyone" on public.album_photos;
create policy "Public album photos are viewable by everyone"
on public.album_photos
for select
to public
using (true);

drop policy if exists "Public resources are viewable by everyone" on public.resources;
create policy "Public resources are viewable by everyone"
on public.resources
for select
to public
using (true);

drop policy if exists "Admins can manage albums" on public.albums;
create policy "Admins can manage albums"
on public.albums
for all
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role in ('admin', 'super_admin')
  )
)
with check (
  exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role in ('admin', 'super_admin')
  )
);

drop policy if exists "Admins can manage album photos" on public.album_photos;
create policy "Admins can manage album photos"
on public.album_photos
for all
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role in ('admin', 'super_admin')
  )
)
with check (
  exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role in ('admin', 'super_admin')
  )
);

drop policy if exists "Admins can manage resources" on public.resources;
create policy "Admins can manage resources"
on public.resources
for all
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role in ('admin', 'super_admin')
  )
)
with check (
  exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role in ('admin', 'super_admin')
  )
);
